<a href="https://colab.research.google.com/github/Priyam023002/ROKO1845/blob/main/First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
''' Generate a numpy array of dimension 1024 x 728 '''
import numpy as np

a_array = np.array([i for i in range(1024)] for j in range(728))

a_array = np.arange(1024*728)
a_array1 = a_array.reshape(1024,728)
print(a_array.shape)
print(a_array1.shape)
print(a_array1.size)
a_array1.reshape(a_array1.size).shape

(745472,)
(1024, 728)
745472


(745472,)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('Digital_marketing.csv')

In [ ]:
zeros = np.zeros((4,3))
print(zeros)

ones = np.ones((4,3))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a_list = [[[1,2,3], [3,4,5]], [[2,4,5], [6,7,8]]]

print(len(a_list))
print(len(a_list[0]))
print(len(a_list[0][0]))

a_array = np.array(a_list)
print(a_array.shape)

2
2
3
(2, 2, 3)


In [ ]:
a = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
list1=[1,2,3,4,5]
a = np.array(list1)

print('list1', list1)
print('numpy array', a)

list1 [1, 2, 3, 4, 5]
numpy array [1 2 3 4 5]


In [ ]:
data=np.array(2)
print(type(data))
lists = [1, 2, 3]
type(lists)

<class 'numpy.ndarray'>


list

In [ ]:
import numpy as np
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
""" f(x) = sqrt(25-x*x) """

import math

def f(x):
  return math.sqrt(abs(25 - x**2))

def f_prime(x):
  if x == -5 or x == 5:
    return 0
  else:
    return -x / math.sqrt(25 - x**2)

def numerical_derivative(x, y, h):
  n = len(x)
  v = [0] * n
  for i in range(n):
    v[i] = (f(x[i] + h) - f(x[i] - h)) / 2*h
    #v[i] = (y[i+1] - y[i-1]) / 2*h
  return v

def estimate_error(v, z):
  return sum(abs(vi - zi) for vi, zi in zip(v, z)) / len(v)

def merge_everything(h):
  x = [-5 + i * h for i in range(int((5 - (-5)/h)))]
  y = [f(xi) for xi in x]
  z = [f_prime(xi) for xi in x]
  v = numerical_derivative(x, y, h)
  error = estimate_error(v, z)
  return x, y, z, v, error

#h = float(input("Enter the value of h: "))
h_values = [0.1, 0.05, 0.02, 0.01]
errors = []

for h in h_values:
    x, y, z, v, error = merge_everything(h)
    errors.append(error)
    print(f"For h = {h:.2f}, E(h) = error = {error:.5f}")

print("All Errors:", errors)




For h = 0.10, E(h) = error = 0.77202
For h = 0.05, E(h) = error = 0.85287
For h = 0.02, E(h) = error = 0.91617
For h = 0.01, E(h) = error = 0.94433
All Errors: [0.7720155775581099, 0.8528710145141342, 0.9161719393533709, 0.9443289350958298]


In [ ]:
! pip install numpy

In [ ]:
z = [0.1,0.9, 34.6, 55, 66, 88.6]
v = [0.001, 3.456, 54.33, 45.67, 55, 78]

for zi, vi in zip(z, v):
  print(zi, vi)

0.1 0.001
0.9 3.456
34.6 54.33
55 45.67
66 55
88.6 78


In [ ]:
""" With an initial list [8,9,10] perform a series of operation (setting the second entry,adding the elements to the end removing the first entry,sorting/doubling the list,inserting an element)."""



In [ ]:
class Vehicles:
  def __init__(self, make, model, year):
    self.make = make
    self.model = model
    self.year = year

  def resale_value(self):
    pass

  def start_engine(self):
    print("Engine started")

  def stop_engine(self):
    print("Engine stopped")

class Car(Vehicles):
  def __init__(self, make, model, year, num_doors):
    super().__init__(make, model, year)
    self.num_doors = num_doors

  def resale_value(self):
    print("Resale Value: xxx")

class Bike(Vehicles):
  def __init__(self, make, model, year, num_gears):
    super().__init__(make, model, year)
    self.num_gears = num_gears

  def resale_value(self):
    print("Resale Value: yyy")

car1 = Car("Toyota", "Innova", 2022, 4)
print(car1.make)
print(car1.model)
print(car1.year)
print(car1.num_doors)
car1.resale_value()
car1.start_engine()
car1.stop_engine()

Bike1 = Bike("Honda", "CBR", 2021, 12)
print(Bike1.make)
print(Bike1.model)
print(Bike1.year)
print(Bike1.num_gears)
Bike1.resale_value()
Bike1.start_engine()

Toyota
Innova
2022
4
Resale Value: xxx
Engine started
Engine stopped
Honda
CBR
2021
12
Resale Value: yyy
Engine started


In [ ]:
""" Object oriented programming language"""
""" Object oriented programming language"""

class Dog:
  def __init__(self, name, breed):
    self.name = name
    self.breed = breed

  def bark(self):
    print("woof! woof!")

dog = Dog("Tommy", "Labrador")
print(dog.name)
print(dog.breed)
dog.bark()

Tommy
Labrador
woof! woof


In [ ]:
''' Guessing !!
generate a random integer and store it in a varriable
Ask the user to guess
At every wrong guess provide whether the useer is below or above the number
'''
import random
number = random.randint(100,500)
guess = 0
guess_left = 3
while guess_left > 0:
  guess = int(input("enter your guess"))
  guess_left -= 1
  if guess == number:
    print("you won")
    break
  elif guess < number:
    print("Your guess is below no:")
  else:
    print("Your guess is above no:")
if guess != number:
  print("you lost", number)


enter your guess512
Your guess is above no:
enter your guess200
Your guess is below no:
enter your guess250
Your guess is below no:
you lost 431


In [ ]:
""" AUC by Trapezoidal Rule including approximation of error  """

import math
import os

def f(x):
  return math.sqrt(25 - x**2)

def trapezoidal_rule(h):
  n = int(5/h)
  x = 0
  A_h = 0

  for i in range(n+1):
    x_next = min(x + h, 5)
    A_h += (x_next - x) / 2 * (f(x) + f(x_next))
    x = x_next
  return A_h

In [ ]:
'''Tasked with creating a program that generates random password.
The password should be eight characters long and include a mix of uppercase letters,lowercase letters,numbers and special characters.''''''To make it even more interesting the program should also classify the generated password as easy,medium or strong based on its complexity'''
password = input("Enter the password")
while len(password) < 8:
  print("Password is too short")
  password = Input("Enter the password Again")
uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
lowercase = "abcdefghijklmnopqrstuvwxyz"
numbers = "0123456789"
special = "!@#$%^&*()_+"

if any(pswrd.islower() for pswrd in password):
  print("Password has lowercase")
else:
  print("Password has no lowercase")
if any(pswrd.isupper() for pswrd in password):
  print("Password has uppercase")
else:
  print("Password has no uppercase")
if any(pswrd.isdigit() for pswrd in password):
  print("Password has numbers")
else:
  print("Password has no numbers")
if any(pswrd.isalnum() for pswrd in password):
  print("Password has special characters")
else:
  print("Password has no special characters")


Enter the passwordpriyam023002
Password has lowercase
Password has no uppercase
Password has numbers
Password has special characters


In [ ]:
"""To classify the generated password as easy,medium or strong based on its complexity"""
sum = 0
for pswrd in password:
  if pswrd.islower():
    sum += 1
  elif pswrd.isupper():
    sum += 2
  elif pswrd.isdigit():
    sum += 3
  elif pswrd.isalnum():
    sum += 1
  elif pswrd in special_chars:
    sum += 1.5
if sum < 11.5:
 print("Password is easy")
elif sum < 24.5:
 print("Password is medium")
else:
 print("Password is strong")

Password is medium


In [ ]:
import random
import string
password = "".join(random.sample(password, 8))

In [ ]:
''' Guessing !!
generate a random integer and store it in a varriable
Ask the user to guess
At every wrong guess provide the following clue:
1)if the guess is less than the number d1 is less than d2(euclidean distance with redpect to minima and maxima 100 and 500 in this case respectively)
'''
import math
import random
number = random.randint(100,500)
guess = 0
guess_left = 3
d1 = math.sqrt((number**2)-(100**2))
d2 = math.sqrt((500**2)-(number**2))
if guess == number:
  print("you won")
break
elif (guess > number) and (d1 < d2):
    print("Your guess is below no:\n")
    print("Hint! No. is towards minima\n")
elif (guess < number) and (d1 > d2):
    print("Your guess is below no:\n")
    print("Hint! No. is towards maxima\n")
if guess != number:
    print("you lost", number)

SyntaxError: invalid syntax (<ipython-input-18-861efc7d5a5b>, line 17)

In [ ]:
print("x=2")

x=2


In [ ]:
import math
result = math.sqrt(484)
print(result)

22.0


In [ ]:
import random
random.randint(1,10)

5

In [ ]:
random.uniform(10,30)

23.16595948245898

In [ ]:
content = input("enter the content")
file = open("file.txt","w")
file.write(content)
file.close()


enter the contentHi, I am doing the pythpn clas


In [ ]:
"""
This is a program for finding prime numbers in the range of 0 to 100
"""
# This loop is for numbers from 2 to 100
for i in range (2,101):
  is_prime = True
  #This is for checking num is prime or not
  for j in range(2,i):
    # IF the num is divisible by the numbers from 2 to num
    if i%j == 0:
      is_prime = False
      print(i, "Not a prime no.")
      #come out of the loop once is_prime is false
      break
  if is_prime == True:
     print(i, "prime no.")

2 prime no.
3 prime no.
4 Not a prime no.
5 prime no.
6 Not a prime no.
7 prime no.
8 Not a prime no.
9 Not a prime no.
10 Not a prime no.
11 prime no.
12 Not a prime no.
13 prime no.
14 Not a prime no.
15 Not a prime no.
16 Not a prime no.
17 prime no.
18 Not a prime no.
19 prime no.
20 Not a prime no.
21 Not a prime no.
22 Not a prime no.
23 prime no.
24 Not a prime no.
25 Not a prime no.
26 Not a prime no.
27 Not a prime no.
28 Not a prime no.
29 prime no.
30 Not a prime no.
31 prime no.
32 Not a prime no.
33 Not a prime no.
34 Not a prime no.
35 Not a prime no.
36 Not a prime no.
37 prime no.
38 Not a prime no.
39 Not a prime no.
40 Not a prime no.
41 prime no.
42 Not a prime no.
43 prime no.
44 Not a prime no.
45 Not a prime no.
46 Not a prime no.
47 prime no.
48 Not a prime no.
49 Not a prime no.
50 Not a prime no.
51 Not a prime no.
52 Not a prime no.
53 prime no.
54 Not a prime no.
55 Not a prime no.
56 Not a prime no.
57 Not a prime no.
58 Not a prime no.
59 prime no.
60 Not a

In [ ]:
"""
This a program for finding leap years in the range of 1900 to 2100
"""
for year in range(1900,2101):
  if year%4 == 0:
    if year%100 != 0:

          print(year, "is a leap year")
          continue
  else:
      if year%400 == 0:
        print(year, "is a leap year")
        continue
      else:
        print(year, "is not a leap year")


1901 is not a leap year
1902 is not a leap year
1903 is not a leap year
1904 is a leap year
1905 is not a leap year
1906 is not a leap year
1907 is not a leap year
1908 is a leap year
1909 is not a leap year
1910 is not a leap year
1911 is not a leap year
1912 is a leap year
1913 is not a leap year
1914 is not a leap year
1915 is not a leap year
1916 is a leap year
1917 is not a leap year
1918 is not a leap year
1919 is not a leap year
1920 is a leap year
1921 is not a leap year
1922 is not a leap year
1923 is not a leap year
1924 is a leap year
1925 is not a leap year
1926 is not a leap year
1927 is not a leap year
1928 is a leap year
1929 is not a leap year
1930 is not a leap year
1931 is not a leap year
1932 is a leap year
1933 is not a leap year
1934 is not a leap year
1935 is not a leap year
1936 is a leap year
1937 is not a leap year
1938 is not a leap year
1939 is not a leap year
1940 is a leap year
1941 is not a leap year
1942 is not a leap year
1943 is not a leap year
1944 is 

In [ ]:
a=-101
b=-21
(a&[(a^b)>>31])|(b&[(a^b)>>31])

TypeError: unsupported operand type(s) for &: 'int' and 'list'

In [ ]:
x = 12
if x < 5:
  print(x)
elif x>2:
  print(x)
else:
  print("x is greater than 5")


12


In [ ]:
science = eval(input("enter science marks"))
maths = eval(input("enter maths marks"))
english = eval(input("enter english marks"))
hindi = eval(input("enter hindi marks"))
sum = science + maths + english + hindi
percentage = sum/400
if percentage >85:
  grade = 'A'
elif percentage > 65:
  grade ='B'a=10
b=20
c=14
d=12
elif percentage > 45:
  grade = 'C'
else:
 grade = 'D'
print("grade is ",grade)

enter science marks91
enter maths marks88
enter english marks87
enter hindi marks81
grade is  D


In [ ]:
a=10
b=20
c=14
d=12
min1=a<d<c<b
min2=b<c<d<a
min3=c<d<a<b
min4=d<a<b<c
min=min1 or min2 or min3 or min4
min_num=(min1*a)+(min2*b)+(min3*c)+(min4*d)
print(min_num)

10


In [ ]:
a=10
b=20
c=14
d=12
if a < b:
  min_ab = a

else:
  min_ab = b
if c < d:
    min_cd = c
else:
    min_cd = d
if min_ab < min_cd:
    print(min_ab)
  else:
    print(min_cd)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 16)

In [ ]:
a=10
b=20
c=14
d=12
if a < b:
  min_ab = a

else:
  min_ab = b
if c < d:
    min_cd = c
else:
    min_cd = d
if min_ab < min_cd:
    print(min_ab)
else: # Aligned 'else' with the 'if' statement above
    print(min_cd)

10


In [ ]:
temp = 100
b_water = 0
while b_water < temp:
  b_water = b_water + 15
  print("Keep checking")
  print(b_water)
  print("Water is boiling")

Keep checking
15
Water is boiling
Keep checking
30
Water is boiling
Keep checking
45
Water is boiling
Keep checking
60
Water is boiling
Keep checking
75
Water is boiling
Keep checking
90
Water is boiling
Keep checking
105
Water is boiling


In [ ]:

bin (0b1100 | 0b1010)

'0b1110'

In [ ]:
a=-10
b=20
print(a&((a|b)>>31))

-10


In [ ]:
# prompt: python code to find sum of first 10 natural numbers




In [ ]:
import sys
print(sys.version)

3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


In [ ]:
print("addition : %d ,multiplication : %d" %(5,3))

addition : 5 ,multiplication : 3


In [ ]:
print("addition : %d ,multiplication : %d" %(5

Enter a string with punctuations : 'HI!!How are you doing?? Data science!"


NameError: name 'remove_punctuation' is not defined